### ISSUE TITLE
Can I add custom parameters

### ISSUE THREAD

**Issue by alexandru-calinoiu** [xinminlabs/newrelic-grape#18]
I will like to add [custom parameters](http://rubydoc.info/github/newrelic/rpm/NewRelic/Agent#add_custom_parameters-instance_method) for my request is this possible?

**Comment by dmitry** [comment]
http://www.rubydoc.info/github/newrelic/rpm/NewRelic/Agent#add_custom_attributes-instance_method should be used instead now.
