### ISSUE TITLE
NewRelic::Rack::AgentHooks#call takes significant amount of time

### ISSUE THREAD

**Issue by benzheren** [xinminlabs/newrelic-grape#23]
We just deployed a new project with `newrelic_rpm 3.9.6.257` and `newrelic-grape 2.0.0`. In all our grape requests, we see significant amount of time is taken by a middleware called `NewRelic::Rack::AgentHooks#call`, which usually takes up more than 50% of the time. 

On the other hand, we used `newrelic_rpm 3.9.1.236` and `newrelic-grape 1.4.1` in an old project. We did not see this behavior. 

I asked the problem on Newrelic Support community, they suggest that it should come from grape instrumentation.

The newrelic community discussion is here: https://discuss.newrelic.com/t/agenthooks-call-spikes-on-latest-ruby-agent-gem/10712

**Comment by dmitry** [comment]
@benzheren have you solved this?

**Comment by benzheren** [comment]
@dmitry it seems that this problem has been resolved.
