### ISSUE TITLE
undefined method `config' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by akshah123** [xinminlabs/newrelic-grape#24]
I am getting undefined method error in my grape application. I believe I followed the example and doc properly but can't figure out why I am getting this error.  here is the stacktrace:

```
undefined method `config' for nil:NilClass (NoMethodError)
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/railties-4.1.2/lib/rails.rb:38:in `configuration'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/newrelic_rpm-3.9.6.257/lib/new_relic/control/frameworks/rails.rb:37:in `rails_config'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/newrelic_rpm-3.9.6.257/lib/new_relic/control/frameworks/rails.rb:49:in `init_config'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/newrelic_rpm-3.9.6.257/lib/new_relic/control/instance_methods.rb:71:in `init_plugin'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/newrelic_rpm-3.9.6.257/lib/new_relic/agent.rb:277:in `manual_start'
  config.ru:40:in `block in <main>'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/passenger-4.0.41/helper-scripts/rack-preloader.rb:112:in `eval'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/passenger-4.0.41/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/passenger-4.0.41/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/passenger-4.0.41/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /home/vagrant/.rvm/gems/ruby-2.1.1/gems/passenger-4.0.41/helper-scripts/rack-preloader.rb:28:in `<main>'
```

any idea on what could be the problem?

**Comment by maneesaj** [comment]
Hello, How did you solve this issue? I'm having a slightly similar issue when trying to do vagrant up:
/Users/maneesa/Homestead/scripts/homestead.rb:60:in `configure': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/maneesa/Homestead/Vagrantfile:17:in `block in <top (required)>'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/loader.rb:97:in `each'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/loader.rb:97:in `block in load'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/loader.rb:94:in `each'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/config/loader.rb:94:in `load'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:614:in `new'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:614:in `vagrantfile'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:399:in `host'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:198:in `block in action_runner'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:33:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:33:in `run'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:386:in `hook'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:596:in `unload'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:177:in `ensure in <main>'
	from /Applications/Vagrant/bin/../embedded/gems/gems/vagrant-1.6.5/bin/vagrant:177:in `<main>'
Maneesas-MacBook-Pro:Homestead maneesa$ cd /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/

**Comment by akshah123** [comment]
@maneesaj looking at your backtrace, it doesn't look like it has anything to do with newrelic-grape project so what worked for me won't work for you.  

For me what worked was making sure newrelic gem was declared before any rails gem.  

In your case, you must have something wrong with your vagrantfile. I would suggest getting some help with vagrant comminuty on their IRC channel. https://www.vagrantup.com/support.html

**Comment by maneesaj** [comment]
Thank you for your help
