### ISSUE TITLE
what does this gem do ?

### ISSUE THREAD

**Issue by chumakoff** [xinminlabs/newrelic-grape#25]
Can you explain what is this gem for ? What does it exactly do ? How to check if it really works ?

**Comment by swistaczek** [comment]
@balauru is it expected that in NewRelic RPM in transactions tab i could only see ```Proc#call```?

**Comment by balauru** [comment]
I know that newrelic gem had some compatibility issues that where fix in the latest version https://discuss.newrelic.com/t/refusing-to-re-register-dependencydetection-block-with-name-grape/13734/2

**Comment by dmitry** [comment]
Looks like it could be closed now.
