### ISSUE TITLE
Warning with grape 0.16

### ISSUE THREAD

**Issue by Arugin** [xinminlabs/newrelic-grape#34]
With grape 0.16.2 I have the next warning:

    .rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/newrelic-grape-2.1.0/lib/newrelic-grape/instrument.rb:32: The route_xxx methods such as route_version have been deprecated, please use version.

**Comment by Arugin** [comment]
any news?

**Comment by flyerhzm** [comment]
please use the official newrelic grape plugin, https://docs.newrelic.com/docs/agents/ruby-agent/frameworks/grape-instrumentation
