### ISSUE TITLE
500 Errors Not Caught By NewRelic

### ISSUE THREAD

**Issue by jwg2s** [xinminlabs/newrelic-grape#6]
Not sure if this is related to #5, but we're not seeing API calls that return a 500 error getting caught by NewRelic's error screen.  Is that an outstanding feature or configuration option I'm missing?

Love this gem, great leap forward for us on API monitoring.

**Comment by jeromegn** [comment]
This is still occurring AFAIK.

I've been able to do it by changing this line: https://github.com/xinminlabs/newrelic-grape/blob/master/lib/newrelic-grape/instrument.rb#L72 to this very hacky line:

```ruby
b.instance_variable_set(:@use, b.instance_variable_get(:@use).unshift(proc { |app| ::NewRelic::Agent::Instrumentation::Grape.new(app) }))
```
